import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "90%",
    padding: 20,
    backgroundColor: "#333333",
    borderRadius: 10,
    alignItems: "center",
    elevation: 10,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 15,
    color: "white",
  },
  secretKeyText: {
    fontSize: 16,
    marginBottom: 15,
    textAlign: "center",
    color: "white",
  },
  header: {
    paddingTop: 60,
  },
  container: {
    flex: 1,
    justifyContent: "center",
    padding: 20,
    paddingTop: 60,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 20,
  },
  balanceContainer: {
    marginTop: 20,
    marginBottom: 20,
  },
  input: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    padding: 10,
    marginBottom: 15,
    backgroundColor: "#f1f1f1",
  },
  barcodeScanner: {
    width: "100%",
    height: "80%",
  },
  detailIcon: {
    position: "absolute",
    top: 5,
    right: 5,
  },
  balanceSection: {
    alignItems: "center",
    marginBottom: 20,
  },
  darkText: {
    color: "#ffffff",
    marginBottom: 10,
  },
  modalView: {
    marginTop: "30%",
    margin: 20,
    backgroundColor: "#333333",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  actionButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 20,
  },
  actionButton: {
    backgroundColor: "#333",
    padding: 15,
    borderRadius: 10,
  },
  sendModalView: {
    width: "90%",
    marginTop: "30%",
    backgroundColor: "#333333",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 15,
    color: "white", // Softer black
  },
  sendButton: {
    backgroundColor: "#28A745", // Green for success action
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 30,
    marginTop: 20,
  },
  sendButtonClose: {
    backgroundColor: "#dc3545", // Red for closing action
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 30,
    marginTop: 10,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
  },
  inputField: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    padding: 10,
    marginVertical: 10,
    color: "#000000",
    placeholderTextColor: "#000000",
  },
  button: {
    borderRadius: 10,
    padding: 10,
    elevation: 2,
    backgroundColor: "#296fc5",
    marginTop: 20,
  },
  sendButtonView: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "30%",
  },
  shareButton: {
    maxWidth: "100%",
    minWidth: "100%",
    backgroundColor: "#296fc5",
    height: "24%",
    textAlign: "center",
    justifyContent: "center",
    fontWeight: "bold",
    borderRadius: 25,
  },
  shareButtonLabel: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    width: "100%",
  },
  buttonClose: {
    backgroundColor: "#f44336",
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "bold",
    color: "#ffffff",
  },
  headerText: {
    textAlign: "center",
    fontSize: 18,
    fontWeight: "bold",
    color: "white",
  },
  addressContainer: {
    backgroundColor: "#333",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 12,
    width: "100%",
  },
  addressText: {
    fontSize: 16,
    textAlign: "center",
    color: "#ffffff",
  },
  balanceText: {
    color: "#ffffff",
    fontSize: 42,
    fontWeight: "bold",
    marginTop: 20,
    textAlign: "center",
  },
  label: {
    fontSize: 18,
    fontWeight: "bold",
  },
  recent: {
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 10,
    width: "100%",
  },
  transactionHistory: {
    marginTop: 20,
    width: "100%",
  },
  fiatBalanceText: {
    color: "#adadad",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
  },
  transactionContainer: {
    backgroundColor: "#d9d9d9",
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  transactionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  transactionType: {
    fontSize: 18,
    fontWeight: "bold",
    marginLeft: 10,
  },
  transactionHash: {
    fontSize: 14,
    color: "#666",
  },
  transactionDate: {
    fontSize: 14,
    color: "#888",
    marginVertical: 5,
  },
  transactionAmount: {
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 10,
  },
  noTransactionsText: {
    fontSize: 16,
    fontStyle: "italic",
    textAlign: "center",
    color: "#888",
    marginTop: 20,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)", // Dimmed background
  },
  receivingStatusText: {
    fontSize: 14,
    color: "#333",
    textAlign: "center",
    marginTop: 5,
  },
  receiveModalContainer: {
    flex: 1,
    justifyContent: "top",
    alignItems: "center",
    backgroundColor: "#1a1a1a",
  },
  receiveHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#333333", // Customize based on your theme
    minWidth: "100%",
  },
  receiveModalView: {
    margin: 20,
    backgroundColor: "#1a1a1a",
    borderRadius: 10,
    padding: 35,
    alignItems: "center",
  },
  receiveIconButton: {
    padding: 8,
  },
  receiveHeaderText: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    color: "white", // Customize based on your theme
  },
  qrContainer: {
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 10,
    marginTop: 20,
  },
  shareButtonLabel: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    width: "100%",
  },
  toastContainer: {
    position: "absolute",
    bottom: 300,
    left: 0,
    right: 0,
    backgroundColor: "#333",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginLeft: 15,
    marginRight: 15,
    alignItems: "center",
  },
  toastContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  toastText: {
    color: "#fff",
    fontSize: 16,
  },
  toastAddress: {
    color: "grey",
    fontSize: 16,
    fontWeight: "bold",
  },

  receiveModalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  receiveModalContent: {
    flex: 1,
    width: "100%",
    backgroundColor: "#1a1a1a",
    borderRadius: 10,
    overflow: "hidden",
    justifyContent: "space-between", // Distributes space between header, body, and footer
  },
  receiveModalBody: {
    alignItems: "center",
    marginTop: -70,
    paddingHorizontal: 20,
  },
  sendButtonView: {
    paddingHorizontal: 20,
    paddingBottom: 50,
  },
});
